tup = (10, "Tulip", 25.5, True, 25.5)
print("Element: ", tup[0])
print("Element: ", tup[-1])
print("Index of the element: ", tup.index('Tulip'))
print("No. of times the element is repeated: ", tup.count(25.5))
my_list = list(tup)
my_list.append('Rose')
tup_list = tuple(my_list)
print("Modified List: ", tup_list)
